mykey = "Izzet_ec2_ssh_key"
ami = "ami-051f8a213df8bc089"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr-1"
jenkins-server-tag = "Jenkins Server of Petclinic"
jenkins-profile = "petclinic-jenkins-server-profile-1"
jenkins-role = "petclinic-jenkins-server-role-1"
